domain: k3s.io

vault:
  chartVersion: 0.27.0
  enabled: true
  namespace: vault-server
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

gitops:
  namespace: argocd

external_secrets:
  enabled: true
  namespace: external-secrets
  chartVersion: 0.14.1
  connectors:
    chartVersion: 0.1.3
  k8sConnector:
    enabled: false

headlamp:
  enabled: true
  namespace: kube-system
  chartVersion: 0.28.1

crossplane:
  enabled: true
  namespace: crossplane-system
  chartVersion: 1.19.0
  configVersion: 0.0.20

keycloak:
  enabled: true
  namespace: keycloak
  chartVersion: 0.0.15

monitoring:
  enabled: true
  namespace: monitoring
  chartVersion: 69.3.1

serverless: 
  enabled: true
  namespace: knative
  chartVersion: v1.17.1

servicemesh: 
  enabled: true 
  namespace: istio-system
  chartVersion: 1.24.3

backstage: 
  enabled: true 
  namespace: backstage
  chartVersion: 0.0.1
