domain: k3s.io

dashboard:
  enabled: true
  namespace: kubernetes-dashboard
  chartVersion: 7.10.4

vault:
  chartVersion: 0.27.0
  enabled: true
  namespace: vault-server
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

gitops:
  namespace: argocd

external_secrets:
  enabled: true
  namespace: external-secrets
  chartVersion: 0.14.1

nfd:
  enabled: true
  namespace: nfd
  chartVersion: 0.17.1