domain: k3s.io

vault:
  chartVersion: 0.27.0
  enabled: true
  namespace: vault-server
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

gitops:
  namespace: argocd

external_secrets:
  enabled: true
  namespace: external-secrets
  chartVersion: 0.14.1
  connectors:
    chartVersion: 0.1.3
  k8sConnector:
    enabled: false

headlamp:
  enabled: true
  namespace: kube-system
  chartVersion: 0.28.1

crossplane:
  enabled: true
  namespace: crossplane-system
  chartVersion: 1.19.0
