apiVersion: apps/v1
kind: Deployment
metadata:
  name: interceptor-deployment
  labels:
    app: interceptor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interceptor
  template:
    metadata:
      labels:
        app: interceptor
    spec:
      containers:
        - name: interceptor
          image: docker.io/cengleby86/interceptor:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: AUTH_URL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: CLIENT_SECRET
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: WEBHOOK_URL
      restartPolicy: Always
