---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: homelab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  providerConfigRef:
    name: keycloak-provider-config
  forProvider:
    realmIdRef:
      name: homelab

    clientSecretSecretRef:
      key: CLIENT_SECRET
      name: homelab-client-secret
      namespace: keycloak

    # Basic client configuration
    name: homelab
    clientId: homelab
    clientAuthenticatorType: client-secret
    accessType: confidential
    enabled: true
    fullScopeAllowed: true
    frontchannelLogoutEnabled: false
    # authorizationServicesEnabled: true
    clientAuthenticatorType: client-secret

    # OpenID Connect specific settings
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    description: Client for Homelab authentication

    # All Open Redirect Acceptable
    validRedirectUris:
      - "*"

    serviceAccountsEnabled: true
# ---
# apiVersion: client.keycloak.crossplane.io/v1alpha1
# kind: ProtocolMapper
# metadata:
#   name: homelab-protocol-mapper
# spec:
#   providerConfigRef:
#     name: keycloak-provider-config
#   forProvider:
#     clientId: homelab
#     consentRequired: false
#     config:
#       full.path: "false"
#       id.token.claim: "true"
#       access.token.claim: "true"
#       claim.name: "groups"
#       userinfo.token.claim: "true"
#     name: groups
#     protocol: openid-connect
#     protocolMapper: oidc-group-membership-mapper
#     realmId: homelab
# ---
# apiVersion: realm.keycloak.crossplane.io/v1alpha1
# kind: OptionalClientScopes
# metadata:
#   name: homelab-optional-client-scopes
# spec:
#   providerConfigRef:
#     name: keycloak-provider-config
#   forProvider:
#     realmId: homelab
#     optionalScopes:
#       - address
#       - phone
#       - offline_access
#       - microprofile-jwt
# ---
# apiVersion: realm.keycloak.crossplane.io/v1alpha1
# kind: DefaultClientScopes
# metadata:
#   name: homelab-default-client-scopes
# spec:
#   providerConfigRef:
#     name: keycloak-provider-config
#   forProvider:
#     realmId: homelab
#     defaultScopes:
#       - web-origins
#       - acr
#       - profile
#       - roles
#       - email
