apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: github-auth
  labels:
    app: sso
    realm: tekton
    client: github-auth
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  client:
    clientId: github-auth
    enabled: true
    name: github-auth
    secret: github-auth-secret
    clientAuthenticatorType: client-secret
    standardFlowEnabled: false
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    publicClient: false
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - roles
      - profile
      - email
    optionalClientScopes:
      - address
      - phone
      - offline_access
      - microprofile-jwt
  realmSelector:
    matchLabels:
      realm: tekton
