apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "keycloak-credentials"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "kubernetes-secrets-store"
    kind: ClusterSecretStore
  target:
    name: "keycloak-credentials"
    template:
      type: generic
      data:
        KEYCLOAK_ADMIN: "{{`{{ .KEYCLOAK_ADMIN }}`}}"
        KEYCLOAK_ADMIN_PASSWORD: "{{`{{ .KEYCLOAK_ADMIN_PASSWORD }}`}}"
  data:
    - secretKey: "KEYCLOAK_ADMIN"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "keycloak-credentials"
        property: KEYCLOAK_ADMIN
    - secretKey: "KEYCLOAK_ADMIN_PASSWORD"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "keycloak-credentials"
        property: KEYCLOAK_ADMIN_PASSWORD