apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "push-secret-keycloak-credentials"
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: keycloak-credentials
  data:
    - match:
        secretKey: "KEYCLOAK_ADMIN_PASSWORD"
        remoteRef:
          remoteKey: keycloak-credentials
          property: "ADMIN_PASSWORD"
    - match:
        secretKey: "KEYCLOAK_ADMIN"
        remoteRef:
          remoteKey: keycloak-credentials
          property: "ADMIN_USERNAME"