apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret-credential-keycloak
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: credential-keycloak
  data:
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: credential-keycloak
      property: ADMIN_PASSWORD
  - secretKey: KEYCLOAK_ADMIN_USERNAME
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: credential-keycloak
      property: ADMIN_USERNAME