apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v1.5.0
