# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: "aws-credentials"
# spec:
#   refreshInterval: "15s"
#   secretStoreRef:
#     name: "kubernetes-secrets-store"
#     kind: ClusterSecretStore
#   target:
#     name: "aws-credentials"
#     template:
#       type: generic
#       data:
#         credentials: |
#           aws_access_key_id={{`{{ .AWS_ACCESS_KEY_ID }}`}}
#           aws_secret_access_key={{`{{ .AWS_SECRET_ACCESS_KEY }}`}}
#   data:
#     - secretKey: "AWS_ACCESS_KEY_ID"
#       remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         metadataPolicy: None
#         key: "aws-credentials"
#         property: AWS_ACCESS_KEY_ID
#     - secretKey: "AWS_SECRET_ACCESS_KEY"
#       remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         metadataPolicy: None
#         key: "aws-credentials"
#         property: AWS_SECRET_ACCESS_KEY