apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "keycloak-credentials"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "kubernetes-secrets-store"
    kind: ClusterSecretStore
  target:
    name: "keycloak-credentials"
    template:
      type: generic
      data:
        credentials: |
          {
            "client_id":"admin-cli",
            "username": "{{`{{ .KEYCLOAK_ADMIN }}`}}",
            "password": "{{`{{ .KEYCLOAK_ADMIN_PASSWORD }}`}}",
            "url": "http://keycloak.rollcage.io",
            "base_path": "/auth",
            "realm": "master",
            "tls_insecure_skip_verify": true
          }
  data:
    - secretKey: "KEYCLOAK_ADMIN"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "keycloak-credentials"
        property: KEYCLOAK_ADMIN
    - secretKey: "KEYCLOAK_ADMIN_PASSWORD"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "keycloak-credentials"
        property: KEYCLOAK_ADMIN_PASSWORD
