apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
              {{- if .Values.vault.enabled }}
                - application: vault-service
                  namespace: "{{ .Values.vault.namespace }}"
                  chart: 
                    name: vault
                    url: https://helm.releases.hashicorp.com
                    version: "{{ .Values.vault.chartVersion }}"
                  values: |
                    csi:
                      enabled: false
                    global:
                      openshift: true
                    injector:
                      enabled: false
                    server:
                      dev:
                        enabled: true
                      enabled: true
                      resources:
                        requests:
                          memory: "128Mi"
                          cpu: "100m"
                        limits:
                          memory: "168Mi"
                          cpu: "150m"
              {{- end }}
              {{- if .Values.external_secrets.enabled }}
                - application: external-secrets-service
                  namespace: "{{ .Values.external_secrets.namespace }}"
                  chart: 
                    name: external-secrets
                    url: https://charts.external-secrets.io
                    version: "{{ .Values.external_secrets.chartVersion }}"
              {{- end }}
              {{- if .Values.efs_driver.enabled }}
                - application: aws-cis-driver
                  namespace: "{{ .Values.efs_driver.namespace }}"
                  chart: 
                    name: aws-efs-csi-driver
                    url: https://kubernetes-sigs.github.io/aws-efs-csi-driver
                    version: "{{ .Values.efs_driver.chartVersion }}"
                  values: |
                    node:
                      env:
                        - name: AWS_ACCESS_KEY_ID
                          valueFrom:
                            secretKeyRef:
                              name: aws-credentials
                              key: aws_access_key_id
                        - name: AWS_SECRET_ACCESS_KEY
                          valueFrom:
                            secretKeyRef:
                              name: aws-credentials
                              key: aws_secret_access_key
              {{- end }}

  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}