apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.serverless.enabled }}
                - application: knative-service
                  namespace: "{{ .Values.serverless.namespace }}"
                  wave: "-3"
                  chart: 
                    name: knative-operator
                    url: https://knative.github.io/operator
                    version: "{{ .Values.serverless.chartVersion }}"
              {{- end }}
              {{- if .Values.servicemesh.enabled }}
                - application: istio-service
                  namespace: "{{ .Values.servicemesh.namespace }}"
                  wave: "-2"
                  chart: 
                    name: base
                    url: https://istio-release.storage.googleapis.com/charts
                    version: "{{ .Values.servicemesh.chartVersion }}"
              {{- end }}
              {{- if .Values.servicemesh.enabled }}
                - application: istio-discovery-service
                  namespace: "{{ .Values.servicemesh.namespace }}"
                  wave: "-1"
                  chart: 
                    name: istiod
                    url: https://istio-release.storage.googleapis.com/charts
                    version: "1.24.3"
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ `{{ .wave }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhooks
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
