apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
              {{- if .Values.vault.enabled }}
                - application: vault-service
                  namespace: "{{ .Values.vault.namespace }}"
                  chart: 
                    name: vault
                    url: https://helm.releases.hashicorp.com
                    version: "{{ .Values.vault.chartVersion }}"
                  values: |
                    csi:
                      enabled: false
                    global:
                      openshift: true
                    injector:
                      enabled: false
                    server:
                      dev:
                        enabled: true
                      enabled: true
                      resources:
                        requests:
                          memory: "128Mi"
                          cpu: "100m"
                        limits:
                          memory: "168Mi"
                          cpu: "150m"
              {{- end }}
              {{- if .Values.external_secrets.enabled }}
                - application: external-secrets-service
                  namespace: "{{ .Values.external_secrets.namespace }}"
                  chart: 
                    name: external-secrets
                    url: https://charts.external-secrets.io
                    version: "{{ .Values.external_secrets.chartVersion }}"
              {{- end }}
              {{- if .Values.dashboard.enabled }}
                - application: kubernetes-dashboard-service
                  namespace: "{{ .Values.dashboard.namespace }}"
                  chart: 
                    name: kubernetes-dashboard
                    url: https://kubernetes.github.io/dashboard/
                    version: "{{ .Values.dashboard.chartVersion }}"
                  values: |
                    app:
                      ingress:
                        enabled: true
                        hosts:
                          - dashboard.rollcage.io
                        ingressClassName: traefik
                        useDefaultAnnotations: true
                        pathType: ImplementationSpecific
                        path: /
                        tls:
                          enabled: false
              {{- end }}

  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}