apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.monitoring.enabled }}
                - application: monitoring-service
                  namespace: "{{ .Values.monitoring.namespace }}"
                  chart: 
                    name: kube-prometheus-stack
                    url: https://prometheus-community.github.io/helm-charts
                    version: "{{ .Values.monitoring.chartVersion }}"
                  values: |
                    grafana:
                      ingress:
                        ingressClassName: nginx
                        enabled: true
                        annotations:
                          nginx.ingress.kubernetes.io/rewrite-target: /
                          nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
                          nginx.ingress.kubernetes.io/ssl-redirect: "true"
                          cert-manager.io/cluster-issuer: letsencrypt
                        hosts:
                          - grafana.rollcage.io
                        tls:
                          - secretName: grafana-service-cert
                            hosts:
                              - grafana.rollcage.io
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
          - ServerSideApply=true
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
