apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-config
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
              {{- if .Values.nfd.enabled }}
                - application: node-feature-discovery-service
                  namespace: "{{ .Values.nfd.namespace }}"
                  wave: "-2"
                  chart: 
                    name: node-feature-discovery
                    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
                    version: "{{ .Values.nfd.chartVersion }}"
                  values: |
                    featureGates:
                      NodeFeatureGroupAPI: true
                    worker:
                      config:
                        core:
                          sleepInterval: 60s
                        sources:
                          pci:
                            deviceClassWhitelist:
                              - "0200"
                              - "03"
                              - "0300"
                              - "12"
                            deviceLabelFields:
                              - "vendor"

              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ `{{ .wave }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
