host: rollcage.io

gitlab:
  enabled: true

catalogs:
  - https://github.com/poc-examples/software-templates/blob/main/catalogs/templates.yaml

backend:
  sqlite3:
    enabled: false
  postgres:
    enabled: true

backstage:
  backstage:
    extraEnvVars:
      - name: BACKSTAGE_FEATURES
        value: "backend-dynamic-feature-service"
    extraAppConfig:
      # - configMapRef: techdocs-plugin
      #   filename: techdocs-plugin.yaml
      # - configMapRef: catalog-config
      #   filename: catalog-config.yaml
      # - configMapRef: tech-radar-plugin
      #   filename: tech-radar-plugin.yaml
      # - configMapRef: kubernetes-plugin
      #   filename: kubernetes-plugin.yaml
    # {{- if .Values.gitlab.enabled }}
    #   - configMapRef: gitlab-plugin
    #     filename: gitlab-plugin.yaml
    # {{- end }}
      # - configMapRef: argocd-plugin
      #   filename: argocd-plugin.yaml
      # - configMapRef: dynamic-plugins
      #   filename: dynamic-plugins.yaml
      - configMapRef: backstage-app-config
        filename: app-config.yaml
      - configMapRef: kubernetes-plugin
        filename: kubernetes-plugin.yaml
      - configMapRef: techdocs-plugin
        filename: techdocs-plugin.yaml
    extraEnvVarsSecrets:
      - postgres-credentials
      - backend-credentials
      - service-account-token
      - keycloak-credentials
      - homelab-client-secret
    extraVolumes:
      - name: backstage-backend-script
        configMap:
          name: backstage-backend-script

    extraVolumeMounts:
      - name: backstage-backend-script
        mountPath: /app/packages/backend/dist/index.cjs.js
        subPath: index.cjs.js
        readOnly: true