kind: ConfigMap
apiVersion: v1
metadata:
  name: techdocs-plugin
data:
  techdocs-plugin.yaml: |
    ##########################
    ## TECHDOCS CONFIGURATION DOCUMENTATION
    ## https://backstage.io/docs/features/techdocs/configuration
    ##########################
    techdocs:
      builder: local
      generator:
        runIn: local
      publisher:
        type: "local"
        local:
          publishDirectory: "/tmp/default/component/"

    ##########################
    ## TECH DOCS CONFIGURATION
    ##########################
    plugins:
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-techdocs
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs:
                routeBindings:
                  targets:
                    - importName: techdocsPlugin
                  bindings:
                    - bindTarget: catalogPlugin.externalRoutes
                      bindMap:
                        viewTechDoc: techdocsPlugin.routes.docRoot
                    - bindTarget: scaffolderPlugin.externalRoutes
                      bindMap:
                        viewTechDoc: techdocsPlugin.routes.docRoot
                dynamicRoutes:
                  - path: /docs
                    importName: TechDocsIndexPage
                    menuItem:
                      icon: docs
                      text: Docs
                  - path: /docs/:namespace/:kind/:name/*
                    importName: TechDocsReaderPage
                mountPoints:
                  - mountPoint: entity.page.docs/cards
                    importName: EntityTechdocsContent
                    config:
                      layout:
                        gridColumn: "1 / -1"
                      if:
                        allOf:
                          - isTechDocsAvailable
                  - mountPoint: search.page.results
                    importName: TechDocsSearchResultListItem
                  - mountPoint: search.page.filters
                    importName: TechdocsSearchFilter
                  - mountPoint: search.page.types
                    importName: techdocsSearchType
                    config:
                      props:
                        name: Documentation
                        icon: docs
