kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: backstage-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: backstage.rollcage.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage-service
                port:
                  number: 7007
  tls:
    - secretName: backstage-service-cert
      hosts:
        - backstage.rollcage.io