kind: ConfigMap
apiVersion: v1
metadata:
  name: techdocs-plugin
data:
  techdocs-plugin.yaml: |
    ##########################
    ## TECHDOCS CONFIGURATION DOCUMENTATION
    ## https://backstage.io/docs/features/techdocs/configuration
    ##########################
    techdocs:
      builder: local
      generator:
        runIn: local
      publisher:
        type: "local"
        local:
          publishDirectory: "/tmp/default/component/"
