apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-client-secret
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: homelab-client-secret
  data:
  - secretKey: CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: homelab-client-secret
      property: CLIENT_SECRET
  - secretKey: CLIENT_ID
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: homelab-client-secret
      property: CLIENT_ID